016/master
ga-wdi-boston/rails-deployment-heroku-study pull request #25
Opened 2017-02-13 20:40 UTC by BenGitsCode

Update talk-template

Refresh for cohort 016

- Minor enhancements to README structure.

2017-02-13 21:06 UTC, jrhorn424 requested changes

2017-02-13 21:06 UTC, jrhorn424 commented on README.md
> +-   [Heroku Rails Deployment](https://devcenter.heroku.com/articles/getting-started-with-rails5)
Great catch!

2017-02-13 21:06 UTC, jrhorn424 commented on README.md
> +-   [ ] Set your secrets using Heroku run.
Heroku run what? I would have done it through the app panel through the browser, or used `heroku config:set KEY=value`

2017-02-13 21:27 UTC, BenGitsCode commented on README.md
> +-   [ ] Set your secrets using Heroku run.
So I just added that to be part of a general check list. Originally that section read like a checklist but skipped some parts (namely setting secrets for your heroku app) and that's a step I saw some people skipping in 015. 

Pushed changes in 0c4da27270cc75d3c76c14fc84506a859a4bb5d6 Is that better?

2017-02-13 21:55 UTC, BenGitsCode commented
I'm confused, did you delete your earlier comment? If so I'm just curious as to why. I can revert the commit if you'd like or adjust it if you disagree with the diff I've made.

2017-02-14 11:23 UTC, jrhorn424 commented
> I'm confused, did you delete your earlier comment?

<img width="768" alt="016_master_by_bengitscode_ _pull_request__25_ _ga-wdi-boston_rails-heroku-setup-guide" src="https://cloud.githubusercontent.com/assets/388761/22927160/d4f96910-f27d-11e6-82f8-444b17c8b3f0.png">

Again, this there is no `heroku run` command to set your secrets. There is, however, a `heroku config:set` command, quoted here from the very section you liked to in your newest commit.

```
heroku config:set SECRET_KEY_BASE=$(rake secret)
```

Please remove references to `heroku run`.

2017-02-14 11:23 UTC, jrhorn424 commented on README.md
> +-   [ ] Set your secrets using Heroku run.
There is no `heroku run` command. See my comment on the PR main thread.

2017-02-14 11:51 UTC, BenGitsCode commented
I updated the language to not say run for the secret setting because that should be set, as you said I had below that. But now I'm really confused. You mean there's no heroku run for secrets, not at all right?

This is the ouptut of `heroku -h`

```sh
Primary help topics, type "heroku help TOPIC" for more details:

  addons    #  manage add-on resources
  apps      #  manage apps (create, destroy)
  auth      #  authentication (login, logout)
  config    #  manage app config vars
  domains   #  manage domains
  logs      #  display logs for an app
  ps        #  manage dynos (dynos, workers)
  releases  #  manage app releases
  run       #  run one-off commands (console, rake)
```

Am i misinterpreting something?

2017-02-14 12:57 UTC, jrhorn424 commented
> Am i misinterpreting something?

Seems so.

Do you see `heroku run` here? `heroku config:set SECRET_KEY_BASE=$(rake secret)`

That `rake` task is being run locally in a subshell, and it's output is being substituted on that line before being updated on heroku.

2017-02-14 13:00 UTC, jrhorn424 commented
I swear I'm not giving you a hard time. But this isn't precise:

> Set your secrets. (Either by using the heroku set command [here](#set-your-secrets) or by using the ...

There is no `heroku set` command. There is `heroku config`, which is the main command for the `set` task.

This isn't pedantry.

Please change the line to read something more simply:

> Set your secrets. (Either by using the [command line](#set-your-secrets) or by using the ...

2017-02-14 13:13 UTC, BenGitsCode commented
I understand, I mistook your previous comment for referring to all references to heroku run, not just within the scope of setting keys—which you're right, is not using precise language. 

Fixed in 01845d1a9247a9d8a31a2f950f40bb09f9652268

2017-02-14 13:16 UTC, jrhorn424 approved these changes

2017-02-14 13:18 UTC, jrhorn424 commented
The update from template was accurate.

This is pedantic: it should have been `study-template`, not `talk-template`. Even more pedantic: it should have been `guide-template`, which doesn't exist.

2017-02-14 13:19 UTC, merged

2017-02-14 13:50 UTC, BenGitsCode commented
I noticed that, and only I went with talk-template as it was the only template recorded in the git log.

Should I create a `guide-template` repo and base it off of this and the other guides? It would be great to have a guide-template in place and start getting uniformity between those repos.